import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Super Word</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen dark:bg-bgdark">
        <div className='w-full md:flex py-4 max-w-5xl mx-auto'>
          <div className='sm:w-full md:w-1/2 px-8'>
            <p className='text-sm text-black dark:text-white'>
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. <span className='bg-orange-200 text-black dark:text-white'>An example of text being highlighted.</span>
            </p>
            <div className='w-full flex justify-end'>
              <div className='dropdown bg-white dark:bg-bgdarkdrop px-1 py-1 mx-2 rounded'>
                <ul>
                  <li className='text-black dark:text-white py-0.5 px-1 bg-bgdarkactivedrop rounded'>Rewrite</li>
                  <li className='text-slate-400 py-0.5 px-1'>Expand</li>
                  <li className='text-slate-400 py-0.5 px-1'>Shorten</li>
                  <li className='text-slate-400 py-0.5 px-1'>Correct</li>
                  <li className='text-slate-400 py-0.5 px-1'>Translate</li>
                </ul>
              </div>
              <div className='dropdown bg-white dark:bg-bgdarkdrop px-1 py-1 mx-2 rounded '>
                <ul>
                  <li className='text-black dark:text-white py-0.5 px-1 bg-bgdarkactivedrop rounded'>English</li>
                  <li className='text-slate-400 py-0.5 px-1'>Spanish</li>
                  <li className='text-slate-400 py-0.5 px-1'>French</li>
                  <li className='text-slate-400 py-0.5 px-1'>Chinese</li>
                  <li className='text-slate-400 py-0.5 px-1'>German</li>
                </ul>
              </div>
              <div className='dropdown bg-white dark:bg-bgdarkdrop px-1 py-1 mx-2 rounded'>
                <ul>
                  <li className='text-black dark:text-white py-0.5 px-1 bg-bgdarkactivedrop rounded'>Friendly</li>
                  <li className='text-slate-400 py-0.5 px-1'>Formal</li>
                  <li className='text-slate-400 py-0.5 px-1'>Angry</li>
                  <li className='text-slate-400 py-0.5 px-1'>Professional</li>
                  <li className='text-slate-400 py-0.5 px-1'>Witty</li>
                </ul>
              </div>
            </div>
          </div>
          <div className='sm:w-full md:w-1/2 px-5'>
            <p className='text-black dark:text-white'>
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. <span className='bg-orange-200 text-black dark:text-white'>An example of text being highlighted.</span>
            </p>
          </div>
        </div>
      </main>
    </>
  )
}
